### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'humanLabel')

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#239]
I am not sure why do I see the error while generating artifacts from [this spec](https://tool.dataspecer.com/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F37aaf868-c462-4639-8117-64723d92796e):
```
Cannot read properties of undefined (reading 'humanLabel')

TypeError: Cannot read properties of undefined (reading 'humanLabel')
    at s (https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:484014)
    at https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:485242
    at h (https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:485428)
    at https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:483911
    at Array.map (<anonymous>)
    at c (https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:483887)
    at https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:487087
    at https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:482714
    at Object.next (https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:482819)
    at https://tool.dataspecer.com/static/js/main.ae0aff2c.chunk.js:1:481730
```
![image](https://user-images.githubusercontent.com/718827/176891933-25fb69b9-08c0-4afc-b748-64ec0df7955d.png)

Maybe it is some older PSMs missing something? I am not even sure whether this is in documentation generator or core.
[artifact (1).zip](https://github.com/mff-uk/dataspecer/files/9028708/artifact.1.zip)

**Comment by jakubklimek** [comment]
It might have something to do with a broken OR in the spec:
![image](https://user-images.githubusercontent.com/718827/176892476-f5fba46b-661c-4d97-86a8-c751c02ef468.png)

**Comment by jakubklimek** [comment]
The OR is no longer in the spec, so this is no longer happening. Closing for now.
