### ISSUE TITLE
Unknown error when generating rdf-to-csv

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#295]
Unknown error when generating rdf-to-csv. In [this specification](https://xn--slovnk-7va.gov.cz/generujeme/specification?dataSpecificationIri=https%3A%2F%2Fofn.gov.cz%2Fdata-specification%2F3efaf255-aec8-45d2-872e-5033cbabc354) when generating zip file with artifacts.

```
Cannot read properties of null (reading 'length')

TypeError: Cannot read properties of null (reading 'length')
    at https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2090816
    at kC (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2090909)
    at vC (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2089386)
    at xC (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2089905)
    at xC (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2090294)
    at bC (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2089785)
    at https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:2092915
    at d (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:1418215)
    at Generator.<anonymous> (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:1419558)
    at Generator.next (https://xn--slovnk-7va.gov.cz/generujeme/static/js/main.b632126d.js:2:1418578)
```

**Comment by JanJanda** [comment]
This is a known issue in the structure model. I have already discussed it with @sstenchlak, and a fix is scheduled in the future. There is some problem with `[refers to]` associations. The `cimIri` is missing. The thrown exception is correct behavior because the value is necessary.
