### ISSUE TITLE
Relationship not generated in vocabulary file

### ISSUE THREAD

**Issue by jakubklimek** [mff-uk/dataspecer#631]
In [this project](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=e27f744e-d71d-4601-ae66-a7d4bbbb2556&view-id=c5d2ee2e-32c6-4c12-abb3-b80410162920) I have defined an "artefact" relationship:
![image](https://github.com/mff-uk/dataspecer/assets/718827/f822ecdd-661d-442a-899d-9316e1581a36)
It is present in the generated documentation:
![image](https://github.com/mff-uk/dataspecer/assets/718827/8e4a777b-8077-4be5-9048-81f405949a1b)
but it is not present in the generated vocabulary file.

**Comment by jakubklimek** [comment]
Also, the lw-onto button does not work:
```
1dd3208c-55c29b4bf9b1abb0.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'iri')
    at m.writeClass (page-20b97c3e5fca7571.js:1:133558)
    at m.generate (page-20b97c3e5fca7571.js:1:132954)
    at t.generate (page-20b97c3e5fca7571.js:1:132035)
    at onClick (page-20b97c3e5fca7571.js:1:86371)
    at Object.aS (1dd3208c-55c29b4bf9b1abb0.js:1:71785)
    at aN (1dd3208c-55c29b4bf9b1abb0.js:1:71939)
    at 1dd3208c-55c29b4bf9b1abb0.js:1:138600
    at sw (1dd3208c-55c29b4bf9b1abb0.js:1:138699)
    at sS (1dd3208c-55c29b4bf9b1abb0.js:1:139113)
    at 1dd3208c-55c29b4bf9b1abb0.js:1:145256
```

**Comment by skodapetr** [comment]
I've fixed a missing argument to the `geenrate` function. It seems that the frontned geenrates the property correctly. Based on a [smaller example](https://tool.dataspecer.com/conceptual-model-editor/diagram?package-id=6b06aba9-7978-4ac7-85ec-58d6faa3043f&view-id=c42437c2-01fa-429c-82fa-e5b17ad832d0) it seems, that the problem is with the detection of the vocabulary to export. 

The relation to export in the example is called "rel1" and is hidden behind the "record"relation.
